version: '3.8'

services:

  # app service
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: crate-php
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
    depends_on:
      - mysql

  # nginx service
  nginx:
    image: nginx:1.19-alpine
    container_name: crate-nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  # mysql service
  mysql:
    image: mysql:latest
    container_name: crate-mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  # phpmyadmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crate-phpmyadmin
    restart: always
    ports:
    - '8086:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql